class Pathes():

    # global_path = 'NBI-Navigator/search_engine/'
    global_path = 'search_engine/'
    # logs_path = 'NBI-Navigator/logs/nbi-navi.log'
    logs_path = 'logs/nbi-navi.log'

    active_clients_name_url_data_path = global_path + 'active_clients_name_url_data.json'
    cacti_urls_path = global_path + 'cacti_urls.json'
    check_client_balance_path = global_path + 'check_client_balance.json'
    client_contract_name_dict_path = global_path + 'client_contract_name_dict.json'
    client_ip_name_dict_path = global_path + 'clien_ip_name_dict.json'
    clients_path = global_path + 'clients.json'
    clients_cash_path = global_path + 'clients_cash.json'
    clients_ip_gateway_mask_dict_path = global_path + 'clients_ip_gateway_mask_dict.json'
    closed_clients_path = global_path + 'closed_clients.json'
    closed_clients_name_url_data_path = global_path + 'closed_clients_name_url_data.json'
    switch_name_ip_dict_path = global_path + 'switch_name_ip_dict.json'
    terminated_clients_name_url_data_path = global_path + 'terminated_clients_name_url_data.json'
    zones_code_path = global_path + 'zones_code.txt'